#!/usr/bin/Rscript

args <- commandArgs(trailingOnly = TRUE)

library(knitr)
opts_chunk$set(eval = FALSE)
rmd = paste("```\n%load_ext rpy2.ipython\n```\n\n", 
  paste(readLines(args[1]), collapse = '\n'),
  collapse = '\n'
)
knit(text = rmd, output = args[2], quiet = FALSE)
warnings()
